## Numpy

- 파이썬에서 수학적 계산을 쉽게 할 수 있도록 도와주는 라이브러리입니다.

In [1]:
import numpy as np

In [9]:
list = ["A", "B", "C", "D", "E"]
list2 = [1,2,3]
array = np.array(list2)
array

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [11]:
print(array.shape)
print(array.ndim)
print(array.dtype)

(5,)
1
<U1


In [13]:
array2 = np.array([["A", "B", "C"], ["D", "E", "F"]])
array2

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [14]:
print(array2.shape)
print(array2.ndim)
print(array2.dtype)

(2, 3)
2
<U1


In [30]:
array3 = np.array(
    [[["A","B","C"]]]
)
array3

array([[['A', 'B', 'C']]], dtype='<U1')

In [31]:
print(array3.shape) # 차원의 요소 개수
print(array3.ndim) # 차원
print(array3.dtype) # data type -> 공통적인 데이터 타입

(1, 1, 3)
3
<U1


In [39]:
array4 = np.array(["1","2","3","4","5"])
print(array4.dtype)

array4 = array4.astype(np.int64)
print(array4.dtype)

<U1
int64


In [40]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[0:3]

array([1, 2, 3])

In [48]:
print(arr > 6)
print(arr[arr > 6])

[False False False False False False  True  True  True]
[7 8 9]


In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

add = np.add(arr1,arr2)
print(add)

multiply = np.multiply(arr1,arr2)
print(multiply)